apiVersion: v2
kubeVersion: '>=1.23.0-0'
name: paintedclouds-hub
description: PaintedClouds Hub Helm chart for Kubernetes
type: application
version: 0.3.0
# renovate: image=ghcr.io/hapsiellx/paintedclouds-hub
appVersion: '0.3.0'
maintainers:
  - name: PaintedClouds Hub maintainers
    url: https://github.com/HapsiellX/paintedclouds-hub
sources:
  - https://github.com/HapsiellX/paintedclouds-hub/tree/main/charts/seerr-chart
home: https://github.com/HapsiellX/paintedclouds-hub
